# -*- coding: utf-8 -*-
"""FULL STEP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16h7vOoX67r69TjDR9j8MoLGjIuGlg2cI
"""

# Commented out IPython magic to ensure Python compatibility.
!nvidia-smi  # Kiểm tra GPU
# %pip install accelerate peft bitsandbytes transformers trl tensorboard
!pip install trl --quiet

import os
import torch
import gc
import pandas as pd
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    logging
)
from peft import LoraConfig
from trl import SFTTrainer, SFTConfig
from google.colab import drive
from tensorboard import notebook

# Giảm phân mảnh bộ nhớ
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'
gc.collect()
torch.cuda.empty_cache()

PROMPTS = {
    "judge_debate": "Please summarize the use of arguments of each debater in the debate and compare them. This includes what arguments are made, whether they are on topic and sound, whether their backing premises and logic are clear and reasonable, whether they are supported by credible evidence, whether the language is appropriate, and whether the counterarguments provide effective refutation against the opponent or fail to respond to some arguments from the opponent. Also analyze the relative strength between each debater's argument sets, and their impacts against each other, by analyzing the clashes between both side's argument sets, comparing the relative strength between sides critically and logically. Award the debater that, within the context of the debate, affirms (for pro) or negates (for con) the resolution the best.",
    "analyze_speech": "Please provide references of the use of arguments in the new speech. This includes what arguments are made, whether they are on topic and sound, whether their backing premises and logic are clear and reasonable, whether they are supported by credible evidence, and whether the language is appropriate.",
    "use_previous": "To clarify arguments already made in the debate, you should refer to previous speeches; you need to report whether the counterarguments provide effective refutation against the opponent, or whether it fails to respond to some arguments from the opponent. In addition, analyze the clashes between both side's argument sets; for each clash, think critically and logically to compare the relative strength between sides.",
    "judge_by_analysis": "First, for each debater, summarize their use of arguments in ALL their debates, according to the given argument analyses. Next, analyze the relative strength between each debater's argument sets, and their impacts against each other; also analyze the clashes between both side's argument sets, comparing the relative strength between sides critically and logically. Award the debater that, within the context of the debate, affirms (for pro) or negates (for con) the resolution the best."
}

from datasets import Dataset
import pandas as pd

def preprocess_winner_only(csv_path):
    df = pd.read_csv(csv_path)
    grouped = df.groupby('conversation_id')
    formatted_data = []

    for conv_id, group in grouped:
        title = group['conversation_title'].iloc[0]
        winner = group['conversation_winner'].iloc[0]

        # Sort by original CSV order
        debate_turns = group.sort_index()

        # Build full debate history
        debate_history = f"Topic: {title}\n\n"
        for _, row in debate_turns.iterrows():
            speaker = row['speaker_name']
            text = row['text']
            speakertype = row['speakertype']
            debate_history += f"{speaker} ({speakertype}): {text}\n\n"

        # Prompt for LLaMA fine-tuning
        prompt = f"<s>[INST] Given the following debate, decide who won.\n\nDebate History:\n{debate_history} [/INST]"
        output = f"The winner is {winner}."

        formatted_data.append({"text": f"{prompt} {output}</s>"})

    return Dataset.from_list(formatted_data)

# Tạo dataset từ CSV
dataset = preprocess_winner_only("/content/debate.csv")

# Khởi tạo tên model
model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
new_model = "TinyLlama-1.1B-chat-finetuned-debate"

from google.colab import drive
import os

# Mount Google Drive at the start
drive.mount('/content/drive')
output_dir = "/content/drive/MyDrive/results_llama2"

# # Function to find the latest checkpoint
# def get_latest_checkpoint(checkpoint_dir):
#     if os.path.exists(checkpoint_dir):
#         checkpoints = [d for d in os.listdir(checkpoint_dir) if d.startswith("checkpoint-")]
#         if checkpoints:
#             latest = max(checkpoints, key=lambda x: int(x.split("-")[1]))
#             return os.path.join(checkpoint_dir, latest)
#     return None

# # Get latest checkpoint if it exists
# resume_from_checkpoint = get_latest_checkpoint(output_dir)
# if resume_from_checkpoint:
#     print(f"Found checkpoint: {resume_from_checkpoint}")
# else:
#     print("No previous checkpoint found, starting fresh training")

from transformers import BitsAndBytesConfig

compute_dtype = torch.float16
quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=False,  # Added for extra memory savings
)

# Remove quantization
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16,  # Use FP16 to save memory
)
model.config.use_cache = False
model.gradient_checkpointing_enable()

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

peft_params = LoraConfig(
    lora_alpha=16,
    lora_dropout=0.1,
    r=64,  # Reduced from 16 to lower memory usage
    bias="none",
    task_type="CAUSAL_LM",
    # target_modules=["q_proj", "v_proj"]
)

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    peft_config=peft_params,
    args=SFTConfig(
        output_dir=output_dir,  # Save to Google Drive
        dataset_text_field="text",
        max_length=2048,  # Reduced from 2048 to speed up training
        packing=False,
        num_train_epochs=3,
        per_device_train_batch_size=4,  # Increased from 4 to reduce steps
        gradient_accumulation_steps=1,  # Adjusted from 2
        optim="paged_adamw_32bit",
        save_steps=25,  # Save more frequently (was 100)
        logging_steps=25,
        learning_rate=2e-4,
        weight_decay=0.001,
        fp16=False,
        bf16=False,
        max_grad_norm=0.3,
        max_steps=-1,  # Run full epoch unless interrupted
        warmup_ratio=0.03,
        group_by_length=True,
        lr_scheduler_type="cosine",
        report_to="tensorboard"
    ),
)

import os
checkpoint_path = "/content/drive/MyDrive/results_tinyllama/checkpoint-2100"
if os.path.exists(checkpoint_path):
    print("Checkpoint directory exists. Contents:")
    print(os.listdir(checkpoint_path))
else:
    print("Checkpoint directory does not exist.")

try:
    # Use the resume_from_checkpoint argument in trainer.train()
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
except Exception as e:
    print(f"Training interrupted: {e}")
    print("Model checkpoints are saved in Google Drive")

# Cell 9: Save final model to Google Drive
try:
    new_model_path = "/content/drive/MyDrive/TinyLlama-1.1B-chat-finetuned-debate"
    trainer.model.save_pretrained(new_model_path)
    tokenizer.save_pretrained(new_model_path)
    print(f"Final model saved to: {new_model_path}")
except Exception as e:
    print(f"Error saving final model: {e}")
    print("You can find the latest checkpoint in the output directory")

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir results/runs

from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM
from peft import AutoPeftModelForCausalLM

import torch
from transformers import logging  # Import logging from transformers

test_debate = [
    {'conversation_id': 10002, 'conversation_title': 'Should social media platforms be regulated to combat misinformation?', 'conversation_winner': 'Alex', 'speaker_name': 'Sam', 'argument_text': "Regulating social media platforms to combat misinformation risks stifling free speech and innovation. Defining 'misinformation' is subjective and can lead to overreach by regulators, potentially silencing valid perspectives. Platforms already have mechanisms like community guidelines and fact-checking partnerships that address harmful content without government intervention. Moreover, users should be trusted to evaluate information critically, rather than relying on top-down censorship.", 'speakertype': 'against'},
    {'conversation_id': 10002, 'conversation_title': 'Should social media platforms be regulated to combat misinformation?', 'conversation_winner': 'Alex', 'speaker_name': 'Alex', 'argument_text': "Social media platforms spread misinformation at an unprecedented scale, influencing public opinion and even elections. Studies, like one from MIT in 2018, show false information spreads six times faster than truth online. Regulation could enforce transparency in algorithms and require platforms to remove demonstrably false content, protecting democracy. Self-regulation has failed—platforms profit from engagement, not accuracy—so government oversight is necessary to ensure accountability.", 'speakertype': 'for'},
    {'conversation_id': 10002, 'conversation_title': 'Should social media platforms be regulated to combat misinformation?', 'conversation_winner': 'Alex', 'speaker_name': 'Sam', 'argument_text': "The MIT study highlights user behavior, not platform failure. People share sensational content, regulated or not. Government oversight introduces bureaucracy and political bias—regulators could favor certain narratives, as seen in some countries with state-controlled media. Platforms like X already experiment with crowd-sourced fact-checking, which is more democratic than top-down rules. Education, not regulation, is the solution to improve media literacy.", 'speakertype': 'against'},
    {'conversation_id': 10002, 'conversation_title': 'Should social media platforms be regulated to combat misinformation?', 'conversation_winner': 'Alex', 'speaker_name': 'Alex', 'argument_text': "Crowd-sourced fact-checking is inconsistent and easily gamed by coordinated groups, as seen in viral misinformation campaigns. Regulation doesn’t mean censorship; it can mandate clear labeling of disputed claims and limit algorithmic amplification of falsehoods. Media literacy is important but slow—regulation offers immediate harm reduction. The 2020 election showed how unchecked misinformation fueled distrust, proving the need for stronger, not weaker, oversight.", 'speakertype': 'for'}
]
logging.set_verbosity(logging.CRITICAL)

# Load the fine-tuned model and tokenizer (adjust output_dir if needed)
output_dir = "/content/drive/MyDrive/TinyLlama-1.1B-chat-finetuned-debate" # Use the actual save path
tokenizer = AutoTokenizer.from_pretrained(output_dir)
model = AutoPeftModelForCausalLM.from_pretrained(
    output_dir,
    device_map="auto",  # Use GPU if available
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    low_cpu_mem_usage=True
)
model = model.merge_and_unload()  # Merge LoRA for inference

# Format the test_debate list into a prompt string matching the training format
prompt = "Given the following debate, decide who won.\n\nDebate History:\nTopic: " + test_debate[0]['conversation_title'] + "\n\n"
for entry in test_debate:
    prompt += f"{entry['speaker_name']} ({entry['speakertype']}): {entry['argument_text']}\n\n"

# Set up the pipeline
pipe = pipeline(task="text-generation", model=model, tokenizer=tokenizer, max_new_tokens=50)  # Use max_new_tokens for generation control

# Generate with the exact training prompt format
result = pipe(f"<s>[INST] {prompt} [/INST]")
print(result[0]['generated_text'])



print(test_debate)

import pandas as pd

# Load the CSV file
df_test = pd.read_csv('/content/test_debate.csv')

# Get the first conversation_id
first_conversation_id = df_test['conversation_id'].iloc[100]

# Filter rows for the first conversation_id
df_filtered = df_test[df_test['conversation_id'] == first_conversation_id]

# Rename 'text' to 'argument_text'
df_filtered = df_filtered.rename(columns={'text': 'argument_text'})

# Convert to list of dictionaries
test_debate1 = df_filtered.to_dict('records')

# Print in the exact format requested
print("test_debate = [")
for i, row in enumerate(test_debate):
    print(f" {{'conversation_id': {row['conversation_id']}, 'conversation_title': '{row['conversation_title']}', 'conversation_winner': '{row['conversation_winner']}', 'speaker_name': '{row['speaker_name']}', 'argument_text': \"{row['argument_text']}\", 'speakertype': '{row['speakertype']}'}}", end="")
    if i < len(test_debate) - 1:
        print(",")
    else:
        print()
print("]")

print(test_debate1)

# Format the test_debate list into a prompt string matching the training format
prompt = "Given the following debate, decide who won.\n\nDebate History:\nTopic: " + test_debate1[0]['conversation_title'] + "\n\n"
for entry in test_debate1:
    prompt += f"{entry['speaker_name']} ({entry['speakertype']}): {entry['argument_text']}\n\n"

# Set up the pipeline
pipe = pipeline(task="text-generation", model=model, tokenizer=tokenizer, max_new_tokens=50)  # Use max_new_tokens for generation control

# Generate with the exact training prompt format
result = pipe(f"<s>[INST] {prompt} [/INST]")
print(result[0]['generated_text'])

print(test_debate)

import pandas as pd

# Load your dataset
df = pd.read_csv('/content/test_debates.csv')  # or pd.read_excel() etc.

# Remove rows where any column contains "It's a tie!"
df = df[~df.apply(lambda row: row.astype(str).str.contains("It's a tie!")).any(axis=1)]

# Remove rows where any column is empty (NaN)
df_cleaned = df.dropna()

# Save the cleaned dataset
df_cleaned.to_csv('test_debate.csv', index=False)

# Cell 8: Run training
trainer.train()

# Cell 9: Save final model to Google Drive
new_model_path = "/content/drive/MyDrive/TinyLlama-1.1B-chat-finetuned-debate"
trainer.model.save_pretrained(new_model_path)
tokenizer.save_pretrained(new_model_path)

log_dir = "./results_tinyllama/runs"
notebook.start(f"--logdir {log_dir} --port 4000")